[project]
name = "p8"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Paul Larribet", email = "plarribet@me.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
p8 = "p8:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
